SET SCHEMA FN71986;

CREATE VIEW INFO
AS
    SELECT T.TICKETID, T.DATE, B.NAME AS STATION_NAME
    FROM TICKETS T, BRANCHES B
    WHERE T.BRANCH_NAME = B.NAME;

SELECT * FROM INFO;

CREATE VIEW INFO2
AS
    SELECT ST.NAME, ST.STAFFID, ST.TELEPHONE, B.ADDRESS
    FROM STAFF ST, BRANCHES B
    WHERE B.NAME = ST.BRANCH_NAME;

