SET SCHEMA FN71986;

CREATE TABLE STAFF(
STAFFID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR(50) NOT NULL,
TELEPHONE CHAR(10) NOT NULL,
BRANCH_NAME VARCHAR(50) NOT NULL,
CONSTRAINT FK_STAFF_BRANCHES FOREIGN KEY (BRANCH_NAME) REFERENCES BRANCHES(NAME) ON DELETE CASCADE
);

CREATE TABLE PASSENGERS(
    EGN CHAR(10) PRIMARY KEY NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    E_MAIL VARCHAR(50) NOT NULL,
    TELEPHONE CHAR(10) NOT NULL,
    CONSTRAINT CK_USERS_VALIDATE_EMAIL CHECK (E_MAIL LIKE '%@%._%')
);

CREATE TABLE BRANCHES(
    NAME VARCHAR(50) PRIMARY KEY NOT NULL,
    ADDRESS VARCHAR(50)
);


CREATE TABLE CARDS(
    CARDID INT NOT NULL,
    EGN CHAR(10) NOT NULL,
    VALIDITY INT NOT NULL ,
    BRANCH_NAME VARCHAR(50),
    CONSTRAINT FK_CARDS_PASSENGERS FOREIGN KEY (EGN) REFERENCES PASSENGERS(EGN) ON DELETE CASCADE ,
    CONSTRAINT PK_CARDS PRIMARY KEY (CARDID, EGN),
    CONSTRAINT FK_CARDS_BRANCHES  FOREIGN KEY (BRANCH_NAME) REFERENCES BRANCHES(NAME) ON DELETE CASCADE

);

CREATE TABLE TICKETS(
    TICKETID INT NOT NULL PRIMARY KEY,
    VALIDITY INT NOT NULL,
    DATE DATE,
    BRANCH_NAME VARCHAR(50) NOT NULL,
    CONSTRAINT FK_TICKETS_BRANCHES  FOREIGN KEY (BRANCH_NAME) REFERENCES BRANCHES(NAME) ON DELETE CASCADE
);

CREATE TABLE SERVS(
    STAFFID INTEGER NOT NULL ,
    EGN CHAR(10) NOT NULL ,
    CONSTRAINT FK_SERVS_STAFF  FOREIGN KEY (STAFFID) REFERENCES STAFF(STAFFID) ON DELETE CASCADE ,
    CONSTRAINT FK_SERVS_PASSENGERS  FOREIGN KEY (EGN) REFERENCES PASSENGERS(EGN) ON DELETE CASCADE,
    CONSTRAINT PK_SERVS PRIMARY KEY(STAFFID,EGN)
);


CREATE TABLE GOES(
    EGN CHAR(10) NOT NULL,
    BRANCH_NAME VARCHAR(50) NOT NULL ,
    CONSTRAINT FK_GOES_PASSENGERS  FOREIGN KEY (EGN) REFERENCES PASSENGERS(EGN) ON DELETE CASCADE ,
    CONSTRAINT FK_GOES_BRANCHES  FOREIGN KEY (BRANCH_NAME) REFERENCES BRANCHES(NAME) ON DELETE CASCADE ,
    CONSTRAINT PK_GOES PRIMARY KEY(EGN,BRANCH_NAME)
);

CREATE TABLE RENEW(
    EGN CHAR(10) NOT NULL ,
    CARDID INT NOT NULL ,
    BRANCH_NAME VARCHAR(50) NOT NULL,
    CONSTRAINT FK_RENEW_CARDS FOREIGN KEY (EGN,CARDID) REFERENCES CARDS(EGN,CARDID) ON DELETE CASCADE,
    CONSTRAINT FK_RENEW_BRANCHES FOREIGN KEY (BRANCH_NAME) REFERENCES BRANCHES(NAME) ON DELETE CASCADE ,
    CONSTRAINT PK_RENEW PRIMARY KEY (EGN,CARDID,BRANCH_NAME)
);

UPDATE BRANCHES SET NAME = 'NKD' WHERE NAME = 'NDK';
